In [21]:
import torch
import numpy as np
from torch.autograd import Variable
import torch.nn as nn
import torch.optim as optim
embedding = nn.Embedding(10, 3)
output = Variable(torch.LongTensor([[0,1,2,3,4,5,6,7,8,9]]))
print(embedding(output))
input = Variable(torch.LongTensor([[4,2,1,5]]))
embedding(input)


tensor([[[-0.0491, -0.8193,  0.2210],
         [-1.4051,  0.3500, -0.4543],
         [-0.3861,  0.1481, -0.8851],
         [ 0.5885, -0.5490, -2.0274],
         [-0.3487, -1.5079,  0.2624],
         [ 0.9531,  1.2678,  0.2727],
         [-1.5148, -1.0978, -0.2168],
         [ 0.5110,  1.1195,  1.9598],
         [ 1.3409,  0.7147, -0.3159],
         [-0.5459, -0.4328, -0.8338]]])


tensor([[[-0.3487, -1.5079,  0.2624],
         [-0.3861,  0.1481, -0.8851],
         [-1.4051,  0.3500, -0.4543],
         [ 0.9531,  1.2678,  0.2727]]])

In [89]:
class Embed(nn.Module):
    def __init__(self):
        super(Embed,self).__init__()
        self.embed = nn.Embedding(10,3)
        self.line = nn.Linear(3,2)
    def forward(self,sentence):
        myembed = self.embed(sentence)
        ans = self.line(myembed)
        return myembed  

In [90]:
mynet= Embed()
loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(mynet.parameters(), lr=0.01)
output = Variable(torch.LongTensor([[0,1,2,3,4,5,6,7,8,9]]))
input = Variable(torch.LongTensor([[0,1,2,3]]))
print(mynet(output))
for epcho in range(10):
    out = mynet(input)
    

tensor([[[ 0.0444, -0.2638, -0.4348],
         [ 0.3070, -0.4930, -2.1831],
         [ 0.7272,  1.8762,  0.0585],
         [-0.9581,  0.9933,  0.9878],
         [ 1.3147, -0.5860,  0.1060],
         [-0.1308, -0.6369, -0.1040],
         [ 0.9592, -1.7291,  0.0919],
         [ 0.0907,  0.3733,  0.2104],
         [-0.2161,  1.2967,  0.2621],
         [ 0.3068,  0.5279, -0.1643]]])


In [94]:
y = np.ones(3)
y = torch.from_numpy(y).long()
print(y)

tensor([ 1,  1,  1])


In [96]:

input = Variable(torch.LongTensor([[4,5,6,7]]))
for epcho in range(10):
    out2 = mynet(input)
    y = y.reshape(1,3)
   # print(y)
    #print(out2)
    loss = loss_function(out2,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
print(mynet(output))

tensor([[[ 0.0444, -0.2638, -0.4348],
         [ 0.3070, -0.4930, -2.1831],
         [ 0.7272,  1.8762,  0.0585],
         [-0.9581,  0.9933,  0.9878],
         [ 1.1153, -0.7849, -0.0929],
         [ 0.0686, -0.4379,  0.0949],
         [ 0.7598, -1.9281, -0.1070],
         [-0.1087,  0.1744,  0.0116],
         [-0.2161,  1.2967,  0.2621],
         [ 0.3068,  0.5279, -0.1643]]])
