In [84]:
class Student(object):
    def __init__(self,name,score):
        self.name = name
        self.score = score
    def print_score(self):
        print('{}:{}'.format(self.name,self.score))
    def get_grade(self):
        if self.score >= 90:
            return "A"
        elif self.score >= 60:
            return "B"
        else:
            return "C"
    
a = Student('mike',99)
b = Student('lisa',30)
a.print_score()
b.print_score()
print(b.get_grade())

mike:99
lisa:30
C


In [1]:
import torch

In [3]:
import numpy as np

In [8]:
x1 = torch.Tensor([3,4])
x2 = torch.FloatTensor([4,4])
x3 = torch.randn(3,4)
print(x1)
print(x2)
print(x3)

tensor([3., 4.])
tensor([4., 4.])
tensor([[-0.8989, -0.5123, -2.2628,  0.3752],
        [ 0.3611, -0.4758,  0.7681, -1.4962],
        [ 1.0481, -2.3021,  1.6014,  0.8783]])


In [24]:
numpy_tensor = np.random.randn(3,5)
pytorch_tensor1 = torch.Tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)
#print(pytorch_tensor1)
#print(pytorch_tensor2)
pt1 = pytorch_tensor1
print(pt1.shape)
print(pt1.numel())

torch.Size([3, 5])
15


In [31]:
mytorch = torch.randn(3,2)
mytorch = mytorch.type(torch.DoubleTensor)
mynumpy = mytorch.numpy()
print(mynumpy.dtype)

float64


In [41]:
x = torch.randn(2,2)
print(x)
y = x.max()
print(y)

tensor([[-1.3030,  0.1863],
        [-1.0772, -0.8897]])
tensor(0.1863)
